name: hackprix_app
description: A Flutter application for seat allotment and admin management for hackers wellbeing at Hackprix.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^3.8.1
  cloud_firestore: ^5.6.0
  firebase_messaging: ^15.2.4
  flutter_local_notifications: ^18.0.1

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.3

flutter:
  uses-material-design: true

  assets:
    - assets/hackprix_logo.png

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/hackprix_logo.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/hackprix_logo.png"
  web:
    generate: true
    image_path: "assets/hackprix_logo.png"
    background_color: "#FFFFFF"
    theme_color: "#2D6BFF"